### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fooloomanzoo**
- link update

### CODE REVIEW

**Comment by supachailllpay** [comment]
Hi @fooloomanzoo thank you for correction.
I just saw your project too. I want to add a demo tab at left side bar, how can I do that? Thanks again.

**Comment by fooloomanzoo** [comment]
There is a script and an instruction on the polymer [pages](https://www.polymer-project.org/1.0/docs/tools/reusable-elements). 
It is for Polymer 1.0 but it still works. For the new iron-component-pages you need to run from [polymer-cli](https://github.com/Polymer/polymer-cli):
`polymer analyze > analysis.json`
Have a look at my [index.html](https://github.com/fooloomanzoo/datetime-picker/blob/master/index.html) after you have done that.
That the demo is not shown directly on `webcomponents.org` might has something to do with the linebreaks after your documentation. For every update on your documentation or code, you have to basically make a new release.

**Comment by fooloomanzoo** [comment]
So basically, instead of: 
```
  <script>

    /**
     * `photo-gallery`
     * A photo gallery element based on Polymer
     *
     * @customElement
     * @polymer
     * @demo demo/index.html
     */

    class PhotoGallery extends Polymer.Element {
      static get is () {
        return 'photo-ga
```

do something like: 
```
  <script>
    /**
     * `photo-gallery`
     * A photo gallery element based on Polymer
     *
     * @customElement
     * @polymer
     * @demo demo/index.html
     */
    class PhotoGallery extends Polymer.Element {
      static get is () {
        return 'photo-ga
```

it could already solve that the demo is not shown.

**Comment by supachailllpay** [comment]
Yeah It works, Thank you for helped me out I will never notice that stuff. 👍

**Pull request merged**
